# top level stuff you probably don't need to touch
gems: [jekyll-paginate]
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title
paginate: 5
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://rubennic.com
baseurl: /
title: Ruben Nic
author: Ruben Nic
description: Projects and Resume
avatar: profile.jpg
email: ruben.niculcea@gmail.com
github: RubenSandwich
twitter: rubenssandwich
