name: Publish Website

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [publish-website]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout solar system clock
        uses: actions/checkout@v4
        with:
          repository: RubenSandwich/fun-projects
          path: ./solar-system-clock/tmp
          sparse-checkout: |
            solar-system-clock

      - name: Install solar-system-clock dependencies
        working-directory: ./solar-system-clock/tmp/solar-system-clock
        run: npm ci

      - name: Build solar-system-clock
        working-directory: ./solar-system-clock/tmp/solar-system-clock
        run: npm run build --if-present

      - name: Move solar-system-clock build
        working-directory: ./solar-system-clock/tmp/solar-system-clock
        run: |
          mv ./dist/* ../../
          cd ../../
          rm -rf ./tmp

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
