name: Publish Website

on:
  push:
    branches: # triggers on any push to master
      - main
  workflow_dispatch: # allows manual trigger

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout solar system clock
        uses: actions/checkout@v4
        with:
          repository: RubenSandwich/fun-projects
          path: ./solar-system-clock/tmp
          sparse-checkout: |
            solar-system-clock

      - name: Set up Node.js
        working-directory: ./solar-system-clock/tmp/solar-system-clock
        uses: actions/setup-node@v3

      - name: Install solar-system-clock dependencies
        working-directory: ./solar-system-clock/tmp/solar-system-clock
        run: npm ci

      - name: Build solar-system-clock
        working-directory: ./solar-system-clock/tmp/solar-system-clock
        run: npm run build --if-present

      - name: Move solar-system-clock build
        working-directory: ./solar-system-clock/tmp/solar-system-clock
        run: |
          mv ./dist/* ../../
          cd ../../
          rm -rf ./temp
          ls

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
